name: Main
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  upload-to-google:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: 'src/thesis/aux/*.pdf'
          folderId: '1QYIBK03dci_H-JtNw_AUjlvtKoSZSdSi'
          overwrite: 'true' # optional boolean
