name: Main
on:
  push:
    branches:
      - 'thesis-skeleton'
  workflow_dispatch:

jobs:
  upload-to-google:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: 'archive.zip'
          folderId: '1k2P5yemljxexE_DFyQmHiDeDgJb0J885'
          name: 'src/thesis/aux/thesis.pdf' # optional string
          overwrite: 'true' # optional boolean
